# Generated by Django 6.0.3 on 2026-04-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name="Anketa ma'lumotlari")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
