# Generated by Django 6.0.3 on 2026-04-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_loanapplication_created_by_loanapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='operator_fish',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
