# Generated by Django 6.0.3 on 2026-04-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_loanapplication_branch_loanapplication_operator_fish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fish',
            new_name='filial_fish',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='fish_inisiali',
            new_name='filial_fish_inisiali',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tashkilot_direktor_fish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tashkilot_direktor_fish_inisiali',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tashkilot_nomi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
